root_path: YOUR_IMAGE_ROOT_PATH
backend: WD14

predictor:
  model_path:
  batch_size: 32
  nproc: -1
  max_chunk: 10

tagger:
  add_tags: []
  prepend_tags: []
  append_tags: []
  include_categories: [General]
  default_threshold: 0.6
  escape_specials: false
  hide_tags: []
  order: alphabetical
  overwrite_mode: replace
  remove_underscores: true
  separator: ','
  token_limit: 70


  custom_threshold_tags:
  - blush
  - facial_mark
  - whisker_markings
  - miqo'te
  custom_thresholds:
  - 0.4
  - 0.1
  - 0.1
  - 0.1

  categories_path:
  tags_path:
