root_path: YOUR_IMAGE_ROOT_PATH # Path to the root folder of your images. Usually not used as the path will be specified in the command line.
backend: WD14 # WD14, WD14-SwinV2 ,WD14-ConvNext or DeepDanbooru. Case sensitive.

predictor:
  model_path: # Path to the model. Leave empty to use models under `models/`.
  batch_size: 32 # Batch size used for inference. Lower it if you get OOM errors.
  nproc: -1 # Number of processes to use for dataloader. -1 means all available.
  max_chunk: 10 # Number of batches to process before a save to the cache file. The default value of 10 is fine for most cases.

tagger:
  add_tags: [] # Tags to add to all images. Can only be used with alphabetical order.
  prepend_tags: []
  append_tags: []
  include_categories: [General] # Categories to include. [General, Character, System] for DeepDanbooru, [General, System] for WD14 taggers
  default_threshold: 0.6
  escape_specials: false # Escape special characters in tags. Usually not needed.
  hide_tags: [] # Bad tags you want to hide from the output. 
  order: alphabetical # alphabetical, probability, probability-reweighted
  overwrite_mode: replace # replace, append, prepend. What to do if the text file already exists.
  remove_underscores: true # Remove underscores from tags. Set false if you are using naifu-diffusion with tag processing.
  separator: ',' # Separator between tags. Use ' ' for naifu-diffusion with tag processing.
  token_limit: 70 # Maximum number of tokens for the output. Start and end tokens, add/prepend/append tags are not counted.

  # Tags that have a custom threshold. The order of the tags must match the order of the thresholds. Notice that the WD14 models' outputs are generally lower than the DeepDanbooru model's output.
  custom_threshold_tags:
  - blush
  - facial_mark
  - whisker_markings
  - miqo'te
  custom_thresholds:
  - 0.4
  - 0.1
  - 0.1
  - 0.1

  categories_path: # Only used for DeepDanbooru. Leave empty unless using a custom category list.
  tags_path: # Leave empty unless using a custom tag list.
